{{- if .Values.PrometheusRules }}
apiVersion: v1
kind: List
items:
{{- range $prometheusRuleName, $prometheusRule := .Values.PrometheusRules }}
  - apiVersion: monitoring.coreos.com/v1
    kind: PrometheusRule
    metadata:
      name: {{ template "prometheus-alerts.fullname" $ }}-{{ $prometheusRuleName }}
      labels:
        {{- include "prometheus-alerts.labels" $ | nindent 8 }}
        role: alert-rules
    spec:
      groups:
{{ toYaml $prometheusRule.groups| indent 8 }}
{{- end }}
{{- end }}
